### ISSUE TITLE
Implement basic AST2vec solution using code2vec paper

### ISSUE THREAD

**Issue by yura-hb** [yura-hb/fit-vylet-2021#1]
**TODO:**

- [x] Implement tree structure
- [x] Implement import of the dataset
- [x] Implement path generation algorithm
- [ ] Implement split of the AST on subtrees, because of the AST complexity
